# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Distribute SNAPSHOT

on: [push, pull_request]

permissions:
  contents: read

jobs:
  dist:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04]
        java: [17]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install graphviz
        run: sudo apt-get install -y graphviz
      - name: Free disk space
        run: |
          echo "Removing large unused packages"
          sudo apt-get remove -y azure-cli google-cloud-sdk microsoft-edge-stable google-chrome-stable powershell mono-devel >/dev/null 2>&1
          sudo apt-get autoclean -y >/dev/null 2>&1
          sudo apt-get clean -y >/dev/null 2>&1
          sudo apt-get autoremove -y >/dev/null 2>&1

          echo "Removing large unused files/directories"
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /usr/local/lib/node_modules /usr/local/share/powershell /usr/local/share/chromium
          sudo rm -rf /opt/ghc /usr/local/share/boost "$AGENT_TOOLSDIRECTORY" /usr/local/graalvm /usr/local/.ghcup

          sudo df -h
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          check-latest: true
      - uses: actions/checkout@v3
      - uses: gradle/gradle-build-action@v2
      - name: Build and package
        run: ./gradlew clean dist --no-build-cache --no-scan --refresh-dependencies
        timeout-minutes: 90
      - name: Move binary distribution
        run:  mkdir -p build/distributions/binary/ && mv subprojects/groovy-binary/build/distributions/apache-groovy-binary-*.zip build/distributions/binary/
      - name: Move src distribution
        run:  mkdir -p build/distributions/src/ && mv subprojects/groovy-binary/build/distributions/apache-groovy-src-*.zip build/distributions/src/
      - name: Move docs distribution
        run:  mkdir -p build/distributions/docs/ && mv subprojects/groovy-binary/build/distributions/apache-groovy-docs-*.zip build/distributions/docs/
      - name: Move sdk distribution
        run:  mkdir -p build/distributions/sdk/ && mv subprojects/groovy-binary/build/distributions/apache-groovy-sdk-*.zip build/distributions/sdk/
      - name: Upload binary distribution
        uses: actions/upload-artifact@v3
        with:
          name: apache-groovy-binary-SNAPSHOT
          path: build/distributions/binary/
      - name: Upload src distribution
        uses: actions/upload-artifact@v3
        with:
          name: apache-groovy-src-SNAPSHOT
          path: build/distributions/src/
      - name: Upload docs distribution
        uses: actions/upload-artifact@v3
        with:
          name: apache-groovy-docs-SNAPSHOT
          path: build/distributions/docs/
      - name: Upload sdk distribution
        uses: actions/upload-artifact@v3
        with:
          name: apache-groovy-sdk-SNAPSHOT
          path: build/distributions/sdk/
